dist: bionic
language: python
python:
  - '3.9'

addons:
  firefox: latest

install:
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz -P ~/
  - tar -xzf ~/geckodriver-v0.29.1-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.29.1-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
  - pip install -r requirements.txt
#  - pip install tchappui-webdrivers

before_script:
#  - install-webdrivers --path /usr/local/bin/
#  - install-webdrivers --path webdrivers

#  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz"
#  - tar xfz geckodriver-v0.29.1-linux64.tar.gz
#  - sudo mv geckodriver /usr/local/bin
#  - 'export DISPLAY=:99.0'
#  - psql -c 'create database better_nutrition;' -U postgres
#  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
#  - sleep 3
#  - python manage.py runserver &


branches:
  only:
    - master

env:
  global:
    - DJANGO_SETTINGS_MODULE="better_nutrition.settings.travis"

services:
  - postgresql

script:
  - python manage.py test
