language: python
python:
- '3.9'

install:
-pip install -r requirements.txt

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="better_nutrition.settings.travis"

services:
-postgresql

script:
-./manage.py test
