language: python
python:
  - '3.8'

addons:
  firefox: latest

install:
  - pip install -r requirements.txt

before_script:
  - install-webdrivers --path webdrivers
#  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz"
#  - tar xfz geckodriver-v0.29.1-linux64.tar.gz
#  - sudo mv geckodriver /usr/local/bin
#  - 'export DISPLAY=:99.0'
#  - psql -c 'create database better_nutrition;' -U postgres
#  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
#  - sleep 3
#  - python manage.py runserver &


branches:
  only:
    - master

env:
  global:
    - DJANGO_SETTINGS_MODULE="better_nutrition.settings.travis"

services:
  - postgresql

script:
  - python manage.py test
