language: python
python:
  - '3.9'

addons:
  firefox: latest


install:
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz -P ~/
  - tar -xzf ~/geckodriver-v0.29.1-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.29.1-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share
  - sudo chmod +x /usr/local/share/geckodriver
  - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
  - pip install -r requirements.txt

before_script:
  - python manage.py runserver &
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate
  - python manage.py commands


branches:
  only:
    - master

env:
  global:
    - DJANGO_SETTINGS_MODULE="better_nutrition.settings.travis"

services:
  - postgresql

script:
  - python manage.py test
