language: python
python:
  - '3.9'

addons:
  firefox: latest

install:
  - pip install -r requirements.txt
  - pip install-webdrivers --path webdrivers

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE="better_nutrition.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
